### ISSUE TITLE
Trigger click event on marker which inside a cluster

### ISSUE THREAD

**Issue by kavishatalsania** [googlemaps/js-markerclusterer#179]
I want to open a info window of a marker which is inside a map cluster. For other marker which are not inside any cluster `google.maps.event.trigger(ourMarker, 'click');` is working as expected, but if marker is inside cluster then it is not working.

Here is a sample example code:  https://codesandbox.io/s/new-bird-8fp0q?file=/src/index.ts

On line 58, I triggered event for marker[0] which is not inside any marker cluster. That is why it is working as expected.

Please change line number 58 to `google.maps.event.trigger(markers[1], "click");` . That will not work because it is inside marker cluster.

Could you please help me with this?

Thanks in advance.

**Comment by jpoehnelt** [comment]
Markers in a cluster are no longer on the map(for performance reasons).

**Comment by kavishatalsania** [comment]
@jpoehnelt  is there anyway we can load markers in the cluster also? And trigger click event?

**Comment by TheAtomicOption** [comment]
The point of the cluster is to replace an excess of markers both visually and for performance, so this isn't really a bug. You would keep all markers on the map by simply not clustering them in the first place. To get a behavior on clicking a cluster, you can define the click event for each cluster (rather than each marker) by defining the onClusterClickHandler of MapClusterer. That should allow you to get whatever behavior you wanted from clicking.

If for some reason you really do want to have _both_ your full set of markers and the clusters they aggregate into on the map at the same time, you can add your original set of markers directly to the map a second time after initializing MapClusterer to get the clusters.

I recommend altering the type tag of this issue from bug to a feature request for an options flag to not remove existing markers when rendering clusters, and deciding whether to close it on that basis.
