### ISSUE TITLE
The Map will be pretty laggy when the length of points is bigger then 5000 and the points is close,especially when I custom the markers

### ISSUE THREAD

**Issue by SmileZXLee** [googlemaps/js-markerclusterer#416]
#### Steps to reproduce
1. init datas more then 5000 and make the points very close.
2. custom the markers like to set a icon.
3. zoom the map to show the markers until the poinst is all spread.
4. and then zoom back to normal,keep repeat the step3 and step4 for several times.
#### Code example
```js
const markers = locations.map((position, i) => {
​      const dotSize = 2;
​      const latlng = new google.maps.LatLng(position.lat, position.lng);
​      const marker = new google.maps.Marker({
​        position: latlng,
​        icon: {
​          path: `M 0, 0 m -${dotSize}, 0 a${dotSize},${dotSize} 0 1,0 ${dotSize *2 },0 a${dotSize},${dotSize} 0 1,0 -${dotSize * 2},0`,
​          fillColor: 'red',
​          fillOpacity: 1.0,
​          scale: 1,
​        },
​        map
​      });
​      return marker;
});

new MarkerClusterer({ markers, map });
```
####

**Comment by amuramoto** [comment]
This is expected behavior that is likely due to known performance issues in the `Marker` class when dealing with large volumes of markers. Usually >300 or so will start to see degraded performance, so it's not too surprising you're running into it with thousands of markers. 

If you need that scale, you could consider something like this [`IconLayer` clustering example](https://deck.gl/examples/icon-layer/) with deck.gl.

**Comment by SmileZXLee** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/29226317/187034198-5c1b0449-0d9e-4efc-a943-e302828f9594.png">
All right, thanks for your reply, it shows "a large number" on the official website of Google Map,I misunderstood it.I think the description should be revised to make the description more accurate and avoid similar puzzled.
