### ISSUE TITLE
Markers are blinking at any action

### ISSUE THREAD

**Issue by Shantarli** [googlemaps/js-markerclusterer#58]
Hey! Thank you so much for this helpful library.
Despite all the good things, I have a big problem that prevents me from using it.
These are blinking markers. At any movement on the map or window size change, a complete redrawing occurs. This behavior is also observed in the example from the google documentation [here](https://developers.google.com/maps/documentation/javascript/marker-clustering) in Safari/Firefox/Chrome, so I will not give an example of my code. It's basically the same.

Version: 1.0.5
Included to the page via unpkg.

Is there any way to overcome this problem, or do I have to wait for a solution for now?
With respect, Roman.

**Comment by jpoehnelt** [comment]
The blinking is partially caused by the algorithms taking map bounds as an input. In some cases, the clustering will remain the same, others it will not. I can see two approaches:

1. Extend viewport to a specific grid encompassing the viewport. This has the tradeoff that some clusters will not be out of the viewport. Not necessarily a blocker though.
2. Add support for caching to the default algorithms based upon some calculation of how much the viewport has changed. This would probably require an additional parameter to `AlgorithmOutput`:

```js
clusters: Clusters[],
changed: boolean,
```

**Comment by jpoehnelt** [comment]
The second option was applied to the SuperClusterAlgorithm which is the default. Please let me know if this works for you!

Thanks again for reporting!
